### PR TITLE
(SERVER-2470) list_all_transports implementation for puppetserver

### PR DESCRIPTION
**Pull request by DavidS**
To test out, run `rake spec_prep` and use the following setup in pry:

```
require 'puppet'
require 'puppet/resource_api/transport'
require 'puppet/settings'

Puppet.initialize_settings
Puppet[:modulepath] = 'spec/fixtures/modules'

# env = Puppet.lookup(:environments).get!('production')
# files = Puppet::Util::Autoload.files_to_load('puppet/transport/schema', env)

Puppet::ResourceApi::Transport.list_all_transports('production')
```

### CODE REVIEW

**Comment by DavidS** [comment]
created draft PR to not lose this code.

**Comment by DavidS** [comment]
The tests pass if the `loads all transports` example runs first:

```
david@davids:~/git/puppet-resource_api$ bundle exec rspec spec/integration/resource_api/transport_spec.rb 

Randomized with seed 35430
/home/david/git/puppet-resource_api/spec/fixtures/modules

Resource API Transport integration tests:
  #list_all_transports
{"test_device"=>#<Puppet::ResourceApi::TransportSchemaDef:0x0000564a43283e60 @data_type_cache={"String"=>#<Puppet::Pops::Types::PStringType:0x0000564a43283d98 @size_type_or_value=nil>, "Optional[String]"=>#<Puppet::Pops::Types::POptionalType:0x0000564a43283cf8 @type=#<Puppet::Pops::Types::PStringType:0x0000564a43283d98 @size_type_or_value=nil>>, "Optional[Array[String]]"=>#<Puppet::Pops::Types::POptionalType:0x0000564a43283c80 @type=#<Puppet::Pops::Types::PArrayType:0x0000564a43283c30 @size_type=nil, @element_type=#<Puppet::Pops::Types::PStringType:0x0000564a43283d98 @size_type_or_value=nil>>>, "Optional[Variant[Array[String], Integer]]"=>#<Puppet::Pops::Types::POptionalType:0x0000564a43283b90 @type=#<Puppet::Pops::Types::PVariantType:0x0000564a43283b40 @types=[#<Puppet::Pops::Types::PArrayType:0x0000564a43283ac8 @size_type=nil, @element_type=#<Puppet::Pops::Types::PStringType:0x0000564a43283d98 @size_type_or_value=nil>>, #<Puppet::Pops::Types::PIntegerType:0x0000564a43283a78 @from=-Infinity, @to=Infinity>]>>}, @attributes={:username=>{:type=>"String", :desc=>"The name of the resource you want to manage."}, :secret=>{:type=>"String", :desc=>"A secret to protect.", :sensitive=>true}, :optional_secret=>{:type=>"Optional[String]", :desc=>"An optional secret to protect.", :sensitive=>true}, :array_secret=>{:type=>"Optional[Array[String]]", :desc=>"An array secret to protect.", :sensitive=>true}, :variant_secret=>{:type=>"Optional[Variant[Array[String], Integer]]", :desc=>"An array secret to protect.", :sensitive=>true}}, @definition={:name=>"test_device", :desc=>"Connects to a device", :connection_info=>{:username=>{:type=>"String", :desc=>"The name of the resource you want to manage."}, :secret=>{:type=>"String", :desc=>"A secret to protect.", :sensitive=>true}, :optional_secret=>{:type=>"Optional[String]", :desc=>"An optional secret to protect.", :sensitive=>true}, :array_secret=>{:type=>"Optional[Array[String]]", :desc=>"An array secret to protect.", :sensitive=>true}, :variant_secret=>{:type=>"Optional[Variant[Array[String], Integer]]", :desc=>"An array secret to protect.", :sensitive=>true}}}>, "test_device_sensitive"=>#<Puppet::ResourceApi::TransportSchemaDef:0x0000564a432834b0 @data_type_cache={"String"=>#<Puppet::Pops::Types::PStringType:0x0000564a43283d98 @size_type_or_value=nil>, "Optional[String]"=>#<Puppet::Pops::Types::POptionalType:0x0000564a43283cf8 @type=#<Puppet::Pops::Types::PStringType:0x0000564a43283d98 @size_type_or_value=nil>>, "Optional[Array[String]]"=>#<Puppet::Pops::Types::POptionalType:0x0000564a43283438 @type=#<Puppet::Pops::Types::PArrayType:0x0000564a43283410 @size_type=nil, @element_type=#<Puppet::Pops::Types::PStringType:0x0000564a43283d98 @size_type_or_value=nil>>>, "Optional[Variant[Array[String], Integer]]"=>#<Puppet::Pops::Types::POptionalType:0x0000564a432833c0 @type=#<Puppet::Pops::Types::PVariantType:0x0000564a43283398 @types=[#<Puppet::Pops::Types::PArrayType:0x0000564a43283348 @size_type=nil, @element_type=#<Puppet::Pops::Types::PStringType:0x0000564a43283d98 @size_type_or_value=nil>>, #<Puppet::Pops::Types::PIntegerType:0x0000564a43283a78 @from=-Infinity, @to=Infinity>]>>}, @attributes={:username=>{:type=>"String", :desc=>"The name of the resource you want to manage."}, :secret_string=>{:type=>"String", :desc=>"A secret to protect.", :sensitive=>true}, :optional_secret=>{:type=>"Optional[String]", :desc=>"An optional secret to protect.", :sensitive=>true}, :array_secret=>{:type=>"Optional[Array[String]]", :desc=>"An array secret to protect.", :sensitive=>true}, :variant_secret=>{:type=>"Optional[Variant[Array[String], Integer]]", :desc=>"An array secret to protect.", :sensitive=>true}}, @definition={:name=>"test_device_sensitive", :desc=>"Connects to a device", :connection_info=>{:username=>{:type=>"String", :desc=>"The name of the resource you want to manage."}, :secret_string=>{:type=>"String", :desc=>"A secret to protect.", :sensitive=>true}, :optional_secret=>{:type=>"Optional[String]", :desc=>"An optional secret to protect.", :sensitive=>true}, :array_secret=>{:type=>"Optional[Array[String]]", :desc=>"An array secret to protect.", :sensitive=>true}, :variant_secret=>{:type=>"Optional[Variant[Array[String], Integer]]", :desc=>"An array secret to protect.", :sensitive=>true}}}>}
    loads all transports
    can be called twice

Finished in 0.05998 seconds (files took 1.05 seconds to load)
2 examples, 0 failures

Randomized with seed 35430

david@davids:~/git/puppet-resource_api$ 
```

**Comment by justinstoller** [comment]
Does this need to implement a custom [Loader](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/pops/loader/loader.rb) to pick up the EnvironmentCache handling?

**Comment by DavidS** [comment]
> Does this need to implement a custom [Loader](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/pops/loader/loader.rb) to pick up the EnvironmentCache handling?

There is follow-up work for cache scoping ticketed up in https://tickets.puppetlabs.com/browse/FM-8092 . For now this is only aiming at unblocking the dumpling team to move forward with their tasks.

**Comment by justinstoller** [comment]
Gotcha, sorry, thought this was for that ticket.

**Pull request merged**
