### PR TITLE
(FM-6797) Add debug logging of current and target states

### PR DESCRIPTION
**Pull request by da-ar**

### CODE REVIEW

**Comment by willmeek** [comment]
+1

**Comment by tphoney** [comment]
👍

**Comment by CmdrCody** [comment]
How can I prevent Sensitive data from leaking onto the Logs when running in debug mode?

I have providers which accept passwords as a parameter, and they are leaking password data when run in debug mode after converting them to using the new SDK/Resource API.

**Comment by DavidS** [comment]
The `Sensitive` problem is now being tracked in https://tickets.puppetlabs.com/browse/PDK-1091

**Pull request merged**
