### PR TITLE
(packaging) Update reported version to 1.8.4 [no-promote]

### PR DESCRIPTION
**Pull request by gimmyxd**

### CODE REVIEW

**Comment by DavidS** [comment]
@mihaibuzgau @gimmyxd please feel free to merge PRs like this at your convenience. I do not understand enough of this process to provide valid review anyways.

**Comment by gimmyxd** [comment]
Something is off with the appveyor build. i can't check it but seems to be still pending :D

**Comment by DavidS** [comment]
closing and re-opening to retrigger appveyor. Doesn't seem like the PR ever made it there.

**Comment by gimmyxd** [comment]
@DavidS can you merge this? seems that i do not have permissions to do that

**Pull request merged**
